### PR TITLE
Use yaml instead of json for the config file

### PR DESCRIPTION
**Pull request by JeLuF**

### CODE REVIEW

**Comment by cmdr2** [comment]
Very nice :)

**Comment by cmdr2** [comment]
I'm okay with merging this, after the current changes in beta (Undo tasks) release to the main branch. Hopefully in a day or two.

Does this PR need any further changes? Ready to merge? (besides the conflict I mean). Thanks

**Comment by JeLuF** [comment]
While reviewing my PR, I noticed that `on_sd_start.sh` is missing in this PR. I'll fix the conflict and the Linux installation tomorrow.

**Comment by cmdr2** [comment]
Thanks! Long pending, and thanks for your patience!

**Pull request merged**
